# Generated by Django 4.2.6 on 2025-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='main/images/')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ReviewsTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rate', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('date', models.DateField(max_length=100, verbose_name='Дата')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('num', models.CharField(max_length=100, verbose_name='Количество персон')),
                ('allergy', models.CharField(max_length=255, verbose_name='Аллергия')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
